data_path: D:\UNH\research\energy consumption\energy_consumption (git)
          
use_lookup: True

use_vehicle_info : False

start_hour: 8

end_hour: 20

time_window: 60 


use_externel: False

use_matrix_fuse: True

observe_length: 12

predict_length: 1


observe_p: 7   #in the day, we observe the 7 first values 

observe_t: 2

test_ratio: 0.2

model_name: LCRNN

model_path: D:\UNH\research\energy consumption\energy_consumption (git)

use_cache_model: False

epochs: 40

batch_size: 1

early_stopping: 2500

learning_rate: 0.001

cvt_spec: 
  NUM_STAGES: 1
  PATCH_SIZE: [6]
  PATCH_STRIDE: [4]
  PATCH_PADDING: [2]
  DIM_EMBED: [120]
  NUM_HEADS: [3]
  DEPTH: [1]
  MLP_RATIO: [4.0]
  ATTN_DROP_RATE: [0.0]
  DROP_RATE: [0.0]
  DROP_PATH_RATE: [0.0]
  QKV_BIAS: [True]
  CLS_TOKEN: [True]
  POS_EMBED: [False]
  QKV_PROJ_METHOD: ['dw_bn']
  KERNEL_QKV: [3]
  PADDING_KV: [1]
  STRIDE_KV: [2]
  PADDING_Q: [1]
  STRIDE_Q: [1]
